### ISSUE TITLE
Easy way to find classifiers

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/ClassifyR#29]
Should we have a function or better documentation to make it easy to see what classifiers are valable?

**Comment by DarioS** [comment]
Perhaps I just update this table with a new column for the keyword used in `crossValidate` (and add the survival models)?

![image](https://user-images.githubusercontent.com/631218/182731990-74279b18-b639-47b9-ab2a-45793e96cc0c.png)

**Comment by DarioS** [comment]
`available()` shows keywords (used for `crossValidate` and also now for `TrainParams` and its ilk) and accompanying descriptions.
