### ISSUE TITLE
Auto detect for ROCplot colours

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/ClassifyR#30]
It would be great to auto select the colours for ROCplot so the default wasn't Classifier Name.

Perhaps if comparison is not provided, and there are no characteristicsLabel, it could automatically paste the non-unique Characteristics values?

**Comment by DarioS** [comment]
Default `comparison` made to be `"auto"` in commit 6bf5f2cfb91ceeb9ba91a064a0ea06e1aadcb5a7
