### ISSUE TITLE
Train function

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/ClassifyR#33]
If would be good to have a train() function to complement predict() for situations where people don't need to run crossValidate.

Effectively this would take most of the same input as crossValidate() and then do a runTest.

One key distinction from crossValidate would be that for multiViewMethod is only fits one model. So by default this should be the full model unless they specify a assayCombination.

**Comment by DarioS** [comment]
A function named `train` doesn't suggest that prediction happens but it would. What about `independentTrainTest`?

**Comment by ellispatrick** [comment]
We have a function called predict. We should also have one called train. I wouldn’t bother with train/test in the same function.

**Comment by DarioS** [comment]
Closed by ba722d29daca99e179efd14f06b41437a1a4be8c
