### ISSUE TITLE
colname error

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/ClassifyR#39]
A better handling of Error in !all.equal(colnames(measurements), make.names(colnames(measurements))) : 
  invalid argument type

**Comment by DarioS** [comment]
Perhaps a 

```r
  if(is.null(colnames(measurements)))
    stop("'measurements' DataFrame must have feature identifiers as its column names.")
```

check is in order, analogous to the one for row names and sample identifiers. Who would do modelling and not care about the feature names (apart from the computer scientists and their obsession with F1 score)?

**Comment by DarioS** [comment]
Resolved some months ago.
