### ISSUE TITLE
Make CoxPH the default selection method for suvival

### ISSUE THREAD

**Issue by Harry25R** [SydneyBioX/ClassifyR#42]
for crossValidate

**Comment by DarioS** [comment]
It would be nice to have that functionality but it would decrease readability of the parameter a bit. Currently, it is `selectionMethod = "t-test"` but it would become something like `selectionMethod = if(is.factor(outcome) || length(outcome) == 1) "t-test" else "CoxPH"`. Unless there's a nicer way, I suppose that I will implement this approach soon.

**Comment by DarioS** [comment]
Yunwei also had this problem today. I implemented `"auto"` default for `selectionMethod` and `classifier` in version 3.3.2. It chooses a t-test/random forest or CoxPH/CoxPH selection-classifier pair depending on what kind of data type `outcome` is.
