### ISSUE TITLE
First Cross-validation Example in Vignette Fails on Some Versions of MacOS

### ISSUE THREAD

**Issue by DarioS** [SydneyBioX/ClassifyR#64]
Some of the summer / international exchange students are reporting problems and the errors only happen for people with MacOS and it seems to be version-specific. I don't have access to Apple computers myself.

- Christine has MacOS Monterey 12.6 and doesn't have the error.
- Cabiria has MacOS Monterey 12.6.2 and has the error.
- Ian has MacOS Ventura 13.0.1 and has the error. Connecting to his department's Linux server in Hong Kong is problem-free.

Also, the Bioconductor check server merida1 uses MacOS Mojave 10.14.6 and doesn't have the error. Is there a modification to avoid it?

**Comment by nick-robo** [comment]
I do not have access to a MacOS machine either, therefore I cannot debug this since I have no way to replicate the error.

**Comment by DarioS** [comment]
I.T. will install R on MacOS computers on ground floor of Carlsaw building at the end of this month, so I may reproduce it.

**Comment by nick-robo** [comment]
Were you able to replicate it?

**Comment by DarioS** [comment]
Error no longer happens using the operating system versions described above. I.T. didn't yet install R in Learning Hub. Grrrrr.
